# Generated by Django 5.0.4 on 2024-05-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='alamat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ttl',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
    ]
