# Generated by Django 5.0.4 on 2024-05-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0003_loginanalytic"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginanalytic",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
