# Generated by Django 5.0.4 on 2024-06-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0004_loginanalytic_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="domisili",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
