# Generated by Django 5.0.4 on 2024-05-05 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KategoriWisata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacation.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Wisata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('harga', models.IntegerField()),
                ('kategori', models.ManyToManyField(through='vacation.KategoriWisata', to='vacation.kategori')),
            ],
        ),
        migrations.AddField(
            model_name='kategoriwisata',
            name='wisata_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacation.wisata'),
        ),
        migrations.CreateModel(
            name='FotoWisata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='wisata/')),
                ('main', models.BooleanField(default=False)),
                ('wisata_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacation.wisata')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.FloatField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wisata_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacation.wisata')),
            ],
        ),
    ]
