# Generated by Django 5.0.4 on 2024-05-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wisata',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='wisata',
            name='kategori',
        ),
        migrations.AddField(
            model_name='wisata',
            name='perizinan',
            field=models.ImageField(default='', upload_to='wisata/izin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fotowisata',
            name='foto',
            field=models.ImageField(upload_to='wisata/gambar'),
        ),
    ]
