# Generated by Django 5.0.4 on 2024-05-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0002_remove_wisata_harga_remove_wisata_kategori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wisata',
            name='perizinan',
            field=models.ImageField(blank=True, null=True, upload_to='wisata/izin'),
        ),
    ]
