# Generated by Django 5.0.4 on 2024-05-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0003_alter_wisata_perizinan'),
    ]

    operations = [
        migrations.AddField(
            model_name='wisata',
            name='gambar_utama',
            field=models.ImageField(blank=True, null=True, upload_to='wisata'),
        ),
    ]
