# Generated by Django 5.0.4 on 2024-05-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0007_wisata_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="wisata",
            name="pilihan",
            field=models.BooleanField(default=False),
        ),
    ]
