# Generated by Django 5.0.4 on 2024-08-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0011_wisata_no_rek_kritiksaran_reportwisate"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReportWisate",
            new_name="ReportWisata",
        ),
    ]
