# Generated by Django 5.0.4 on 2024-08-13 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0012_rename_reportwisate_reportwisata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservasiWisata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pembayaran", models.ImageField(upload_to="wisata/pemabayaran")),
                ("nama", models.CharField(max_length=255)),
                ("no_wa", models.CharField(max_length=15)),
                ("hari", models.DateField()),
                ("jumlah", models.IntegerField()),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wisata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vacation.wisata",
                    ),
                ),
            ],
        ),
    ]
