# Generated by Django 5.0.4 on 2024-08-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0014_wisata_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="wisata",
            name="biaya",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
