# Generated by Django 5.0.4 on 2024-08-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0015_wisata_biaya"),
    ]

    operations = [
        migrations.AddField(
            model_name="kritiksaran",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
