# Generated by Django 5.0.4 on 2024-08-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0017_travelagency_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportwisata",
            name="tanggal",
            field=models.DateField(blank=True, null=True),
        ),
    ]
