# Generated by Django 5.0.4 on 2024-08-14 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0018_reportwisata_tanggal"),
    ]

    operations = [
        migrations.AddField(
            model_name="wisata",
            name="kategori",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vacation.kategori",
            ),
        ),
        migrations.DeleteModel(
            name="KategoriWisata",
        ),
    ]
