# Generated by Django 5.0.4 on 2024-08-14 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0019_wisata_kategori_delete_kategoriwisata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wisata",
            name="kategori",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vacation.kategori",
            ),
        ),
    ]
