# Generated by Django 5.0.4 on 2024-08-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0020_alter_wisata_kategori"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservasiwisata",
            name="online",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reservasiwisata",
            name="pembayaran",
            field=models.ImageField(
                blank=True, null=True, upload_to="wisata/pemabayaran"
            ),
        ),
    ]
