# Generated by Django 5.0.4 on 2024-08-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0021_reservasiwisata_online_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wisata",
            name="publish",
            field=models.BooleanField(default=False),
        ),
    ]
