# Generated by Django 5.0.4 on 2024-08-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0022_wisata_publish"),
    ]

    operations = [
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gambar_utama",
                    models.ImageField(blank=True, null=True, upload_to="information"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="wisata",
            name="publish",
        ),
    ]
