# Generated by Django 5.0.4 on 2024-08-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0023_information_remove_wisata_publish"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservasiwisata",
            old_name="online",
            new_name="fullpayment",
        ),
        migrations.AddField(
            model_name="wisata",
            name="high_season",
            field=models.BooleanField(default=False),
        ),
    ]
