# Generated by Django 5.0.4 on 2024-08-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0024_rename_online_reservasiwisata_fullpayment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wisata",
            name="show_rating",
            field=models.BooleanField(default=False),
        ),
    ]
