# Generated by Django 5.0.4 on 2024-08-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0025_wisata_show_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelagency",
            name="is_hotel",
            field=models.BooleanField(default=False),
        ),
    ]
