# Generated by Django 5.0.4 on 2024-08-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0026_travelagency_is_hotel"),
    ]

    operations = [
        migrations.AddField(
            model_name="wisata",
            name="maks",
            field=models.IntegerField(default=0),
        ),
    ]
