# Generated by Django 5.0.4 on 2024-08-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0027_wisata_maks"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="hide",
            field=models.BooleanField(default=False),
        ),
    ]
